/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SIpPortRouteImport } from './routes/s.$ip.$port'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SIpPortRoute = SIpPortRouteImport.update({
  id: '/s/$ip/$port',
  path: '/s/$ip/$port',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/$ip/$port': typeof SIpPortRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$ip/$port': typeof SIpPortRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s/$ip/$port': typeof SIpPortRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/s/$ip/$port'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/$ip/$port'
  id: '__root__' | '/' | '/s/$ip/$port'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SIpPortRoute: typeof SIpPortRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$ip/$port': {
      id: '/s/$ip/$port'
      path: '/s/$ip/$port'
      fullPath: '/s/$ip/$port'
      preLoaderRoute: typeof SIpPortRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SIpPortRoute: SIpPortRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
